kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-manager-binding
subjects:
- kind: User
  name: cy-user
  apiGroup: "rbac.authorization.k8s.io"
roleRef:
  kind: ClusterRole
  name: deployment-manager-cluster
  apiGroup: "rbac.authorization.k8s.io"
