# prometheus.yml
global:
  scrape_interval: 15s 
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
rule_files:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:30000"]
  - job_name: "python-app"
    static_configs:
      - targets: ["localhost:3100"] 

