apiVersion: v1
kind: Service
metadata:
  labels:
    name: ping
  name: ping
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: ping
    app: demo
    role: frontend
