apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ambassador-conf
data:
  default.conf: |
    upstream backend {
        server production-app-svc weight=2;
        server experiment-app-svc weight=1;
    }

    server {
        listen 4000;
        server_name _;
        location / {
            proxy_pass http://backend;
        }
    }
