apiVersion: v1
kind: Pod
metadata:
  name: secret-volume
spec:
  containers:
    - name: test-container
      image: nginx:alpine
      volumeMounts:
      - name: secret-volume
        mountPath: /tmp/config
  volumes:
    - name: secret-volume
      secret:
        secretName: mysecret 
  restartPolicy: Never
