apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-deployment
  labels:
    app: nginx
    owner: cloudyuga
spec:
  replicas: 3
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [nginx]}
      - {key: owner, operator: NotIn, values: [admin]}
  template:
    metadata:
      labels:
        app: nginx
        owner: cloudyuga
    spec:
      containers:
      - name: nginx
        image: teamcloudyuga/nginx:alpine
        ports:
        - containerPort: 80
