apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cars.crds.cloudyuga.guru
spec:
  group: crds.cloudyuga.guru
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                brand:
                  type: string
                review:
                  type: boolean
                replicas:
                  type: integer
  scope: Namespaced
  names:
    plural: cars
    singular: car
    kind: Car 
    shortNames:
     - car


