apiVersion: v1
kind: Pod
metadata:
  name: single-container-logs
spec:
  containers:
  - name: first-container
    image: teamcloudyuga/busybox:1.28
    args:
    - /bin/sh
    - -c
    - >
      i=0;
      while true;
      do
        echo "$i: $(date)"
        i=$((i+1));
        sleep 3;
      done

