apiVersion: v1
kind: Pod
metadata:
  name: nginx-liveness
  labels:
     app: nginx
spec:
  containers:
  - name: nginx-demo
    image: teamcloudyuga/nginx:alpine
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 5
      timeoutSeconds: 1
