apiVersion: v1
kind: Pod
metadata:
  name: readiness-tcp
spec:
  containers:
  - name: echo-server
    image: teamcloudyuga/http-echo:0.2.3
    args: ["-listen", ":8080", "-text", "example for tcp readiness probe"]
    ports:
      - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 1
