apiVersion: batch/v1
kind: Job
metadata:
  name: nginx
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name: nginx
      labels:
        app: job
    spec:
      containers:
      - name: nginx
        image: teamcloudyuga/nginx:alpine
        command: ["/bin/sh"]
        args: ["-c", "echo Hello World"]
      restartPolicy: Never
