apiVersion: v1
kind: Pod
metadata:
  name: busybox-apparmor
  annotations:
    # Tell Kubernetes to apply the AppArmor profile "k8s-apparmor-example-deny-write".
    # Note that this is ignored if the Kubernetes node is not running version 1.4 or greater.
    container.apparmor.security.beta.kubernetes.io/busybox: localhost/k8s-apparmor-example-deny-write
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command: [ "sh", "-c", "echo 'Hello AppArmor!' && sleep 1h" ]
