apiVersion: v1
kind: Pod
metadata:
  name: nginx-no-requests-no-limits
  labels:
     app: nginx
spec:
  containers:
  - name: nginx
    image: teamcloudyuga/nginx:alpine
    ports:
    - containerPort: 80
