apiVersion: v1
kind: Pod
metadata:
  namespace: quota-mem-cpu-example
  name: nginx
  labels:
     app: nginx
spec:
  containers:
  - name: nginx-demo
    image: teamcloudyuga/nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "4Gi"
        cpu: "2"      
      requests:
        memory: "1Gi"
        cpu: "1"
