apiVersion: v1
kind: Pod
metadata:
  name: nginx-no-requests
  labels:
     app: nginx
spec:
  containers:
  - name: nginx
    image: teamcloudyuga/nginx:alpine
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "400Mi"
        cpu: "0.3"      
