apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu
  namespace: quota-mem-cpu-example
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: 512Mi
    limits.cpu: "1"
    limits.memory: 1Gi
