kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-manager-binding
  namespace: cloudyuga
subjects:
- kind: User
  name: nkhare
  apiGroup: "rbac.authorization.k8s.io"  
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: "rbac.authorization.k8s.io"
