apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  selector:
    matchLabels:
      app: python
  replicas: 2
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python-app
        image: teamcloudyuga/custom-python-app
        ports:
        - name: web
          containerPort: 3100