apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: teamcloudyuga/nginx:1.9.1
    ports:
    - containerPort: 80
    volumeMounts:
    - name: secret
      readOnly: true
      mountPath: /data/db
   volumes:
   - name: secret
     secret:
       secretName: mysecret
