apiVersion: v1
kind: Pod
metadata:
  name: cpu-load
spec:
  containers:
  - name: cpu-load
    image: polinux/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    command: ["stress"]
    args: ["--cpu", "2"]
